
torchrun --nproc_per_node=1 main.py \
    --test_only \
    --train_data /root/data/train_with_relevant_triples_wounkrel.pkl \
    --eval_data /root/data/dev_with_relevant_triples_wounkrel.pkl \
    --test_data /root/data/test_with_relevant_triples_wounkrel.pkl \
    --relation2id /root/data/relation2id.pkl \
    --relationid2name /root/data/relationid2name.pkl \
    --init_relation_embedding /root/data/relation_t5base_embeddings.pkl \
    --model_size base \
    --text_maxlength 250 \
    --k 20 \
    --hop 3 \
    --n_context 10 \
    --name default_experiment \
    --checkpoint_dir checkpoint \
    --lr 1e-4 \
    --scheduler fixed \
    --weight_decay 0.01 \
    --per_gpu_batch_size 2 \
    --accumulation_steps 16 \
    --clip 1.0 \
    --total_steps 15000 \
    --eval_freq 500 \
    --save_freq 15000 \
    --saved_checkpoint_path checkpoint/default_experiment/checkpoint_epoch4_step15000.ckpt \
